### ISSUE TITLE
Gradient amp response not matching simulation

### ISSUE THREAD

**Issue by ghost** [jaystock/Open_Source_MRI_Tools_MGH#15]
Step response is not accurate

**Comment by ghost** [comment]
Confirmed that capacitors matched simulation value of 470 pF, and tested a single output channel instead of 2 combined -- no fix

**Comment by jaystock** [comment]
We found that a 24V supply was inadequate to drive more than ~4.5 amps in the low field scanner gradient coils.  One potential solution is to add a second 24V supply in series to provide 50V to drive more current and also help handle the high inductances for rapid slewing.

**Comment by jaystock** [comment]
One option for powering buffers would be to use a standard +/-15V regulator to power the INA105s.

**Comment by ghost** [comment]
Splitting off comments to a different issue
