### ISSUE TITLE
Document choke on wiki

### ISSUE THREAD

**Issue by ghost** [jaystock/Open_Source_MRI_Tools_MGH#24]

**Comment by jaystock** [comment]
Photos of the 3T and 7T chokes --> include physical dimensions for the former, the STL model for the former, the number of wire turns, and the number of added turns near feed point, if used
Rendering of the FEKO model
Include the FEKO model files for other users
Include calibrated S11 impedance measurements of 3T and 7T chokes on the end of open-ended BNC
Add sniffer coil S11 of the self-resonance
Include a plot of self-resonance from FEKO (scale will be different)

**Comment by ghost** [comment]
Working documentation added
