### ISSUE TITLE
Measure contrast to noise for 4-coil EIT, replacing material balls

### ISSUE THREAD

**Issue by ghost** [jaystock/Open_Source_MRI_Tools_MGH#40]
Complicated capture process, do in person with Jason

**Comment by jaystock** [comment]
Jason made progress with measuring the S-parameter matrix using a motor to lower the ball through the phantom in a controlled manner.

**Comment by jaystock** [comment]
Preparation of figures for the grant is finished.  We have some idea of the contrast to noise ratio (CNR) for the EIT experiments, and some ideas for how to improve the CNR in future versions of the experiment.
