### ISSUE TITLE
Check bypass capacitors in Bill of Materials to make sure they can handle a 50 Volt supply voltage.

### ISSUE THREAD

**Issue by jaystock** [jaystock/Open_Source_MRI_Tools_MGH#44]
Ignore the bypass capacitors that only see the 5V regulator output for the digital components.  We just care about the bypass caps on the main 48V line that are placed near the OPA549s.

**Comment by ghost** [comment]
Ordered -- combining actual soldering with https://github.com/stockmann-lab/Open_Source_MRI_Tools_MGH/issues/41
