### ISSUE TITLE
Document preamp statistics and components

### ISSUE THREAD

**Issue by ghost** [jaystock/Open_Source_MRI_Tools_MGH#5]

**Comment by jaystock** [comment]
Include S11 and S21 from VNA between 0.1 MHZ and 1 GHZ
Include measurements from the tabletop scanner where the same gain is used for the Miteq and Lincoln's LNA
SNR on a single readout can be computed as peak magnitude of the spectrum divided by standard deviation of the noise near the edge of the spectral window
Include GERBERs and KICAD files as well as Bill of Materials
Optional: Include image later

**Comment by ghost** [comment]
Completed
